import './globals.css'
import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Udaysk Portfolio',
  description: 'Generated by create next app',
}

 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Udaysk Portfolio</title>
        <link rel="icon" type="image/x-icon" href="/letter-u.png"/> 
      </head>
      <body className={inter.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}

